### PR TITLE
prettifications, abstract and links

### PR DESCRIPTION
**Pull request by Nikolaj-K**
Minor text prettifications

### CODE REVIEW

**Comment by buckysballs** [comment]
Thanks! Can you pls compile and commit the a pdf with the changes? Then will merge 👍

**Comment by Nikolaj-K** [comment]
Done.
Also removed the duplicated .txt file from the root directory.

**Comment by Nikolaj-K** [comment]
@buckysballs Since a README was missing, I also went ahead and took the README form the other files and prefixed it with the abstract from Matheos current outstanding PR. 
You may me if I should revise this or merge other branches in or what else I could stratify when I'll read through it the next days.

**Comment by Nikolaj-K** [comment]
Put the core part of the readme text to the abstract and added a sentence of you from the feedback I saw in the channels.

**Comment by Nikolaj-K** [comment]
Adding a link to this economics-model repo to the resource list in a PR here

https://github.com/Constellation-Labs/awesome-constellation/pull/2

**Comment by Nikolaj-K** [comment]
I now read through the text! 

Changelog:
Edited a collection of word repetitons, articles and missing commas. I also tried to reduce the number of explainer brackets by incooporating their content into the text in a smooth way - unless it was really just an auxiliary specification. I put \emph around introductions of new terms.
All equations were labeled “eq1”, so I fixed that.
Some sentences could be split into 2 sentences for clarity.
In one place I replaces “discreet gradient” with “discrete gradient”. I assume that was a typo but maybe it was a notion I don’t know, in which case please point it out and I make a commit reverting it. 
I put the two less verbose mathematical expression as inline formulas. The manifold M is \mathcal{M} here now, which I usually see, but again, tell me if you take offence with those styles.
At one point in the third section, when you set up the concept of computational volume, you jumped from throughput to processing power, but I think you mean both and I added the respective other expression the second time it’s mentioned.
I moved the link explaining Signed Observation Edge up to where it’s first introduced.
In one place you were taking a sum over just “r” but the terms had index i, so I assume what makes sense here is you meant “i\,\in\,\{1, \dots, r\}” and I made that replacement.
What I didn’t get was the expression “effect that the protocol has”, that’s mentioned in the diffeomorphism paragraph. The r-form \omega is not re-introduced here before it’s used.
I replaced “Deficiency” with “Reduction” where you speak of entropy, tell me if you explicitly wanted to say Deficiency here?
I replaced “Result” with “Discussion” at the end, which seems more fitting to me here.

Thoughts: 
Firstly, I get that those volume integral as well as the entropy computations contribute to the evaluation of the nodes performances - it would be interesting to add how frequently those global (when taken together) data are evaluated, and how this evaluation is intended to be performed. I see how the capturing of the data necessary for the computation can or will be stored in a distributed fashion, but I’m not sure where this data is gathered and computed, so that rewards can be rewarded. I get that the nodes have a means of computing other nodes reputation, but it’s not yet clear how this computation and distribution is performed - I think that’s not part of the setup yet, in any case.
Secondly, You don’t actually mention “optimization of the network topology” much until the end. Maybe suited for another text or maybe worth a comment in the middle.

**Comment by buckysballs** [comment]
* This amounts to the effect that the protocol has on the total configuration space. => should say "the transformation".

**Comment by buckysballs** [comment]
Thanks @Nikolaj-K !

**Comment by Nikolaj-K** [comment]
@buckysballs Ah, I can see where protocol<->transformation was coming from, as "protocol" in a way represents also all algorithms running on the network. I guess it's a term with too many interpretations now.

Btw. note the PR with the addition of this repo in the list that I linked at the end
https://github.com/Constellation-Labs/awesome-constellation/pull/2

**Pull request merged**
